server {
    listen       80 reuseport default_server;
    listen       [::]:80 reuseport default_server;
    server_name  _;
    return       444;

    error_page 400 405 = @close_conn;
    location @close_conn {
        return   444;
    }
}

server {
    listen       443 ssl reuseport default_server;
    listen       [::]:443 ssl reuseport default_server;
    listen       443 quic reuseport default_server;
    listen       [::]:443 quic reuseport default_server;
    server_name  _;

    ssl_reject_handshake on;
    ssl_certificate      /etc/nginx/certs/default_server.crt;
    ssl_certificate_key  /etc/nginx/certs/default_server.key;
    ssl_stapling         off;
    ssl_stapling_verify  off;

    return       444;

    # 捕获HTTP明文请求访问 HTTPS 端口的内部错误 (497状态码) 静默关闭连接
    error_page 400 405 497 = @close_conn;
    location @close_conn {
        return   444;
    }
}
