#!/usr/bin/env bash

if [ "$#" -lt 1 ]; then
    echo "Not enough arguments!"; exit 1
fi

HOSTS=(kafka01 kafka02 kafka03)

# 遍历集群中的所有机器
for host in "${HOSTS[@]}"; do
    echo "===================  $host  ==================="

    # 遍历所有提供的文件参数
    for file in "$@"; do
        if [ -e "$file" ]; then
            # 获取绝对父目录路径
            pdir=$(cd -P "$(dirname "$file")" && pwd)
            # 获取文件名
            fname=$(basename "$file")

            # 在远程主机上创建目录（如果不存在）
            ssh "$host" "mkdir -p $pdir"
            # 将文件同步到远程主机
            rsync -av "$pdir/$fname" "$host:$pdir"
        else
            echo "$file does not exist!"
        fi
    done
done