services:
  tools:
    image: corentinth/it-tools:2024.10.22-7ca5933
    container_name: tools
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - TZ=Asia/Shanghai
    networks:
      - tools

networks:
  tools:
    driver: bridge