services:
  memos:
    image: neosmemo/memos:0.22.5
    restart: unless-stopped
    container_name: memeos
    hostname: memeos
    ports:
      - 5230:5230
    volumes:
      - ./memos:/var/opt/memos
    networks:
      - memeos

networks:
  memeos:
    driver: bridge