services:
  myip:
    image: jason5ng32/myip:v4.4.0
    container_name: myip
    restart: unless-stopped
    ports:
      - 18966:18966
    networks:
      - myip

networks:
  myip:
    driver: bridge