services:
  stirling-pdf:
    image: frooodle/s-pdf:0.36.0
    container_name: s-pdf
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=zh_CN
    volumes:
      - ./trainingData:/usr/share/tessdata
      - ./extraConfigs:/configs
      - ./logs:/logs
    networks:
      - s-pdf

networks:
  s-pdf:
    driver: bridge