services:
  redis:
    image: redis:7.4.0-alpine3.20
    container_name: searxng_db
    restart: unless-stopped
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    image: searxng/searxng:2024.12.1-0245e82bd
    container_name: searxng
    restart: unless-stopped
    networks:
      - searxng
    ports:
     - 8080:8080
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE

networks:
  searxng:
    driver: bridge